### PR TITLE
Convert expires property to date object

### PR DESCRIPTION
**Pull request by xavierdutreilh**
As mentioned in #38, the cookie is created for the current session only. This is due to the fact that the `expires` property passed to cookie-cutter is a number, and not a date.

The present request fixes this by converting the timestamp to a date.

### CODE REVIEW

**Comment by 4nduril** [comment]
Please just merge this. I am having the very same problem.

**Comment by 4nduril** [comment]
Great, thank you very much! When you have the time, please publish a new patch-version to npm.

**Comment by dy** [comment]
@4nduril done.

**Comment by kastsiushkin** [comment]
Hi guys, I'm still seeing cookie being set for session on iOS, Chrome looks fine.

**Pull request merged**
