### PR TITLE
Flat design with autofixing

### PR DESCRIPTION
**Pull request by GabLeRoux**
Based on https://github.com/kudago/smart-app-banner/pull/32 work

I added [husky](https://github.com/typicode/husky) for easy automatic precommit git hook.
[eslint](https://github.com/eslint/eslint) and [xo](https://github.com/sindresorhus/xo) to auto format js
[stylelint](https://github.com/stylelint/stylelint) and [stylefmt](https://github.com/morishitter/stylefmt) to auto format css

I fixed he linter's issues, should still work fine.
Test page works fine;

ios-7-8-smart-app-banner
<3

So when we commit:
>  git commit                                                   
> 
> > smart-app-banner@1.3.0 precommit <snip>/node_modules/smart-app-banner
> > xo --fix index.js && fixmyjs && stylefmt smart-app-banner.css && npm run test && npm run build
> 
> 
> > smart-app-banner@1.3.0 test <snip>/node_modules/smart-app-banner
> > xo
> 
> 
>   smart-app-banner.js
>   ⚠  File ignored because of a matching ignore pattern. Use "--no-ignore" to override.
> 
>   1 warning
> 
> > smart-app-banner@1.3.0 build <snip>/node_modules/smart-app-banner
> > browserify index.js -s SmartBanner | ccjs - > smart-app-banner.js
> 
> (node:24405) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
> The compiler is waiting for input via stdin.
> [flat-design-with-autofixing 0371321] Merge remote-tracking branch 'kudago/master' into flat-design-with-autofixing

### CODE REVIEW

**Comment by dy** [comment]
Is it possible in any way to get rid of all format-related suggestions and leave only style fixes, in the original format/code style/other preferences? I would really appreciate that.

**Comment by GabLeRoux** [comment]
Style fixes were done using the automated tools above, I only applied the same logic for the js.

The point here is that most of the js changes were done automatically by `xo --fix` So once this is merged, everyone contributing to this repo in the future will use the same style guide. Changes with "wrong indentation" or "forgot to build with latest change" shouldn't happen again. On the js side, that's only linting fixes and having such mechanism is a great way to avoid white space merge conflicts by using the same coding style for everyone without having to worry about it. Here for example, the cssh change for ios style banner was blocked since september 2015 only because of bad formatting. Let's eliminate this for good.

I personally find that not having to worry about indentation and forcing lint on a project is kind of a good idea in general. Reviews will focus on changes to the features, not the syntax.

Anyway, I understand the hesitation here. I did the js changes recommanded by the linter and nothing more, everything else is just autofixing from the tools. Unless I missed something, there wasn't a defined code style specified before.

If you still think only css should change here and that we should remove eslint and xo, I'm ok with that too ;)

Oh and by the way, we should provide a minified version of the css as well ;)

**Comment by dy** [comment]
The point totally makes sense by itself, not along with iOS updates. But changes are mostly for good, so let formatting be.
The only thing I don’t like is big devDeps stack, is it possible to reduce it to `eslint` only?

**Comment by jrobichaud** [comment]
I believe this is a good solution to avoid blocking awesome pull requests because of different coding styles.

**Comment by GabLeRoux** [comment]
I removed fixmyjs and jshint, but I kept husky, xo, stylefmt and eslint.

**Pull request merged**
