### PR TITLE
rely on tested ua-parser-js instead of non-tested solution

### PR DESCRIPTION
**Pull request by iamstarkov**
as titled

### CODE REVIEW

**Comment by iamstarkov** [comment]
@dfcreative @glibin piu

**Comment by iamstarkov** [comment]
@everyonesdesign can you take a look?

**Comment by everyonesdesign** [comment]
@iamstarkov 
Merged
Thank you very much for the commits

**Comment by iamstarkov** [comment]
=) @everyonesdesign can you publish new version?

**Comment by everyonesdesign** [comment]
OK, done

**Pull request merged**
