### PR TITLE
Enable to pass innerHTML as an option

### PR DESCRIPTION
**Pull request by ohbarye**
Hello @dfcreative , thanks to provide great OSS.

Trying to create my app with `smart-app-banner`, I thought that it would be useful to render the banner's HTML as a user like. Then I forked and changed to realize that.

It would be nice if you would pull this, thanks.

### CODE REVIEW

**Comment by dy** [comment]
Hi @obarye!
Why don't just create element, what is the purpose of smartbanner in that case?

**Comment by ohbarye** [comment]
What I wanted to do first is putting a link to my web site like below. 
add_link

And now, I have to change the DOM of the banner in order to change banner design more radically. (And I'm planning A/B test for the banner in the future.)

Of course I can create or manipulate elements at out of this library, but I assume it's not elegant way.
What do you think?

**Comment by dy** [comment]
I am still not sure what is has to do with the smart-app-banner and why you need it in your case. If all the purpose of smart-app-banner is mobile detection, better use something like [is-mobile](http://npmjs.org/package/is-mobile) package. It would be way more elegant.

**Comment by ohbarye** [comment]
Hmm, what I have to do is not only mobile detection but also creating my original banner with smart-app-banner, but as you said, I may be able to realize it with other package. So I'll try it.

Then I'll close this, thanks for your advice.

**Pull request closed without merging**
