### PR TITLE
Display on iOS if not Safari.

### LINKED ISSUE #34: Does not display smart banner for Chrome on iOS 6+
The logic currently hides the banner for anything on iOS 6+. However a user may be using a browser other than Safari, such as Chrome and will not see the smart banner. Ideally this library would only hide if also using Safari.

### PR DESCRIPTION
**Pull request by nanek**
Fixes #34

### CODE REVIEW

**Comment by Gedzis** [comment]
👍

**Comment by dy** [comment]
Could you just remove smart-app-banner.js from the PR?

**Comment by nanek** [comment]
Updated.

**Comment by CavalcanteLeo** [comment]
Does it fix the duplicate banner?

**Comment by CavalcanteLeo** [comment]
@renanmonteiros

**Review by GabLeRoux — APPROVED** [review]

**Comment by GabLeRoux** [comment]
Code looks fine. I did not personally reproduce #34 tho. On my side, the native banner doesn't show up at all (but I'm using an older version/fork in production). 

We should definitely use some tools to confirm this. [BrowserStack is free for open source projects](https://www.browserstack.com/open-source). I would be very happy to have some kind of verification for these problems. I suppose we can get screenshots of multiple devices to confirm this.

Having two banners is definitely annoying and should not happen.

**Pull request closed without merging**
