### PR TITLE
Double banner on iOS fix

### PR DESCRIPTION
**Pull request by tomek-f**
Fix for os.vesion like '9.3.2' that returns NaN

### CODE REVIEW

**Comment by DaSchTour** [comment]
The same as #75

**Comment by DaSchTour** [comment]
The problem is also handled in #68

**Comment by Chrysweel** [comment]
+1
In my ipad, I see double navbar!

**Comment by theonicolaou** [comment]
I can also see the native banner and plugin banner (in iOS 10.2, iPhone SE). Is there an ETA for a fix for this?

**Comment by danhodkinson** [comment]
the fix is relatively straightforward. the issue is with this part:
`Number(agent.os.version) >= 6`

it seems to have an issue with the 10.3.2 term.
Instead you can just use `parseFloat(agent.os.version)` or `parseInt(agent.os.version)` which will give you an actual number to test against.

So hopefully this gets PR'd soon. But for anybody looking for a fix.. it's simple to update yourself

**Comment by mauritsvanrees** [comment]
I can confirm that this helps.
I would say this is slightly better than the fix in #75 because that one does not explicitly use a radix of 10 for `parseInt`, and a radix is [recommended](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#ECMAScript_5_Removes_Octal_Interpretation). But there may be other [opinions](http://stackoverflow.com/questions/850341/how-do-i-work-around-javascripts-parseint-octal-behavior) and it may not matter in this case because apple probably does not report a zero in front of its version numbers.

**Comment by Ericky14** [comment]
Hello,

Is this branch getting merged to master anytime soon?

**Comment by lucaboieru** [comment]
Hello!

Any progress with this pull request? Can someone merge it if everything is okay? I think the demand for this fix is quite high.

**Pull request merged**
