### PR TITLE
Dispatching customized events

### PR DESCRIPTION
**Pull request by caeugusmao**
Making possible dispatch events during the "smart banner" life cycle

### CODE REVIEW

**Comment by caeugusmao** [comment]
Hi Kudago,

I am Carlos Gusmão, software engineer from Globo.com(http://globo.com). 

Two months ago I opened a pull request to make possible dispatch custom events during smart banner life cycle.
Could you take a look in my pull request, please? I am waiting that to finish my smart app banner.

Tks and best regards,

Carlos Gusmão

**Comment by dy** [comment]
Hi @caeugusmao!

I could not find a use-case for that and how is it better than just running code after creating a banner.

**Comment by caeugusmao** [comment]
Hi @dfcreative!

We need to know when the banner was loaded and how the banner is created asynchronously I believe that custom events are the best form to solve this kind of problem . The event enables I know if banner is already loaded and trigger another functions that depend the smart banner loaded. 

Another form to solve this problem is trigger a callback after banner is loaded, but I prefer events.

Do you know another way to my use-case?

Thanks for listening! 

Carlos Gusmão

**Comment by dy** [comment]
There is no much of async to introduce events pattern.
If you are afraid to run code before banner is ready, you can force your code be invoked inside of `DOMContentLoaded` event.
Otherwise I would recomment just include smartbanner at the end of the document - that way you can safely run your code after banner in sync way.

As for async patterns there are [events](https://www.npmjs.com/package/events) core module, promises and node-style callbacks, the last is preferrable in such simple cases.

**Pull request closed without merging**
